name: Build Apps

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install "PySide6[webengine]"
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --windowed --name FirstPass --collect-all matplotlib --collect-all matplotlib.backends --collect-all backend_qt5agg --collect-all backend_qtagg --collect-all plotly --collect-all pandas --collect-all numpy --collect-all torch --collect-all sentence_transformers --collect-all PySide6 --collect-all transformers --collect-all seaborn --collect-all scipy --collect-all statsmodels --collect-all category_encoders --collect-all openai --collect-all anthropic --collect-all cryptography --collect-all wordcloud --collect-all yfinance --collect-all geopy --collect-all folium --collect-all networkx --collect-all tabulate --collect-all httpx windows.spec

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: FirstPass-Windows
        path: dist/FirstPass.exe

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install "PySide6[webengine]"
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --windowed --name FirstPass --collect-all matplotlib --collect-all matplotlib.backends --collect-all backend_qt5agg --collect-all backend_qtagg --collect-all plotly --collect-all pandas --collect-all numpy --collect-all torch --collect-all sentence_transformers --collect-all PySide6 --collect-all transformers --collect-all seaborn --collect-all scipy --collect-all statsmodels --collect-all category_encoders --collect-all openai --collect-all anthropic --collect-all cryptography --collect-all wordcloud --collect-all yfinance --collect-all geopy --collect-all folium --collect-all networkx --collect-all tabulate --collect-all httpx macos.spec

    - name: Create DMG
      run: |
        cd dist
        hdiutil create -volname "FirstPass" -srcfolder FirstPass.app -ov -format UDZO FirstPass.dmg

    - name: Upload Mac artifacts
      uses: actions/upload-artifact@v4
      with:
        name: FirstPass-macOS
        path: |
          dist/FirstPass.app
          dist/FirstPass.dmg