name: Build Apps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4
    
    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install "PySide6[webengine]"
        pip install auto-py-to-exe
        
    # Step 4: Build the executable with auto-py-to-exe
    - name: Build with auto-py-to-exe
      run: |
        python -m auto_py_to_exe --cli --output-dir dist --onefile --console --name FirstPass
        
    # Step 5: Upload the Windows artifact
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v2
      with:
        name: FirstPass-Windows
        path: dist/FirstPass.exe

  build-macos:
    runs-on: macos-latest
    
    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4
    
    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install "PySide6[webengine]"
        pip install auto-py-to-exe
        
    # Step 4: Build the executable with auto-py-to-exe
    - name: Build with auto-py-to-exe
      run: |
        python -m auto_py_to_exe --cli --output-dir dist --onefile --console --name FirstPass
        
    # Step 5: Create DMG file for macOS
    - name: Create DMG
      run: |
        cd dist
        hdiutil create -volname "FirstPass" -srcfolder FirstPass -ov -format UDZO FirstPass.dmg
        
    # Step 6: Upload the macOS artifacts
    - name: Upload Mac artifacts
      uses: actions/upload-artifact@v2
      with:
        name: FirstPass-macOS
        path: |
          dist/FirstPass
          dist/FirstPass.dmg
