name: Build Apps

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install "PySide6[webengine]"
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --collect-all plotly --collect-all pandas --collect-all numpy --collect-all torch --collect-all sentence_transformers --collect-all PySide6 --collect-all transformers main.py

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: FirstPass-Windows
        path: dist/main.exe

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install "PySide6[webengine]"
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --collect-all plotly --collect-all pandas --collect-all numpy --collect-all torch --collect-all sentence_transformers --collect-all PySide6 --collect-all transformers main.py

    - name: Create DMG
      run: |
        cd dist
        hdiutil create -volname "FirstPass" -srcfolder main -ov -format UDZO FirstPass.dmg

    - name: Upload Mac artifacts
      uses: actions/upload-artifact@v4
      with:
        name: FirstPass-macOS
        path: |
          dist/main
          dist/FirstPass.dmg