name: Build Apps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4  # Ensure using the latest version for checking out the repository
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install "PySide6[webengine]"
        pip install auto-py-to-exe
        
    - name: Build with auto-py-to-exe
      run: |
        cd /Users/runner/work/firstpass-app/firstpass-app  # Ensure you're in the correct working directory
        python -m auto_py_to_exe --cli --output-dir dist --onefile --console --name FirstPass main.py  # Reference to the main.py in the root
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: FirstPass-Windows
        path: dist/FirstPass.exe

  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4  # Ensure using the latest version for checking out the repository
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install "PySide6[webengine]"
        pip install auto-py-to-exe
        
    - name: Build with auto-py-to-exe
      run: |
        cd /Users/runner/work/firstpass-app/firstpass-app  # Ensure you're in the correct working directory
        python -m auto_py_to_exe --cli --output-dir dist --onefile --console --name FirstPass main.py  # Reference to the main.py in the root
        
    - name: Create DMG
      run: |
        cd dist
        hdiutil create -volname "FirstPass" -srcfolder FirstPass -ov -format UDZO FirstPass.dmg
        
    - name: Upload Mac artifacts
      uses: actions/upload-artifact@v4
      with:
        name: FirstPass-macOS
        path: |
          dist/FirstPass
          dist/FirstPass.dmg
