name: Build Apps

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch the full repository history

    - name: List Files in Directory
      run: |
        echo "Working Directory:"
        pwd
        echo "Files:"
        dir  # Windows command to list files

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install "PySide6[webengine]"
        pip install auto-py-to-exe

    - name: Build with auto-py-to-exe
      run: |
        python -m auto_py_to_exe --cli --output-dir dist --onefile --console --name FirstPass ./main.py

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: FirstPass-Windows
        path: dist/FirstPass.exe

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch the full repository history

    - name: List Files in Directory
      run: |
        echo "Working Directory:"
        pwd
        echo "Files:"
        ls -al  # macOS command to list files

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install "PySide6[webengine]"
        pip install auto-py-to-exe

    - name: Build with auto-py-to-exe
      run: |
        python -m auto_py_to_exe --cli --output-dir dist --onefile --console --name FirstPass ./main.py

    - name: Create DMG
      run: |
        cd dist
        hdiutil create -volname "FirstPass" -srcfolder FirstPass -ov -format UDZO FirstPass.dmg

    - name: Upload Mac artifacts
      uses: actions/upload-artifact@v4
      with:
        name: FirstPass-macOS
        path: |
          dist/FirstPass
          dist/FirstPass.dmg
